version: "3.8"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn h4ev.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8006:8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
